paramHFOV:                1.045
paramVFOV:                0.815
paramWidth:               640
paramHeight:              480
paramProbHit:             0.50
paramProbMiss:            0.30
paramMaxRange:            10.0
paramOccupancy:           0.5
paramVoxelSize:           0.50
paramForceRaycast:        true
paramErodeThreshold:      0.2
paramDensityThreshold:    20
paramPointCloudTopic:     /pointcloud/depth/color/points
paramCloudTargetFrame:    /odom
paramCloudSourceFrame:    /heifu0/camera_link
