# Xbox 360 wireless controller
# Deadman (enable) button: Right Bumper
teleop:
  gimbal:
    type: service
    service_name: /heifu0/gimbal/setAxes
    service_request:
      roll: 0
      pitch: 0
      yaw: 0
    axis_mappings:
      - axis: 2  # Right thumb stick (left/right)
        target: roll
        scale: 1.0
        offset: 0.0
      - axis: 1  # Right thumb stick (up/down)
        target: pitch
        scale: 1.0
        offset: 0.0
      - axis: 0  # Left thumb stick (left/right)
        target: yaw
        scale: 1.0
        offset: 0.0
    service_persistent: False # False by default
    buttons: [6]

