-   topic   : /$(arg argNamespace)/outVelStamped
    type    : geometry_msgs/TwistStamped
    timeout : 0.5
    priority: 100

-   topic   : /$(arg argNamespace)/planners/local_position/setpoint
    type    : uav_msgs/UAVWaypoint
    timeout : 0.2
    priority: 105

-   topic   : /$(arg argNamespace)/outVelStampedPrime
    type    : geometry_msgs/TwistStamped
    timeout : 5.0
    priority: 110

-   topic   : /$(arg argNamespace)/outPoseStamped
    type    : geometry_msgs/PoseStamped
    timeout : 5.0
    priority: 200

-   topic   : /$(arg argNamespace)/waypointsManager/goalWaypoint
    type    : uav_msgs/UAVWaypoint
    timeout : 0.0
    priority: 205

-   topic   : /$(arg argNamespace)/outWaypoint
    type    : uav_msgs/UAVWaypoint
    timeout : 0.0
    priority: 250

-   topic   : /$(arg argNamespace)/landingWaypoint
    type    : uav_msgs/UAVWaypoint
    timeout : 0.0
    priority: 250

-   topic   : /$(arg argNamespace)/collisionAvoidance/emergencyStop
    type    : geometry_msgs/TwistStamped
    timeout : 1.0
    priority: 254
